server:
  port: 40404

spring:
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为 testWhileIdel 执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle 中为 select 1 from dual)
      validation-query: select 1
      # 申请连接时会执行 validationQuery 检测连接是否有效,开启会降低性能,默认为 true
      test-on-borrow: false
      # 归还连接时会执行 validationQuery 检测连接是否有效,开启会降低性能,默认为 true
      test-on-return: false
      # 是否缓存 preparedStatement, 也就是 PSCache，PSCache 对支持游标的数据库性能提升巨大，比如说 oracle,在 mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于 0，当大于 0 时，poolPreparedStatements 自动触发修改为 true。
      # 在 Druid 中，不会存在 Oracle下 PSCache 占用内存过多的问题，可以把这个数值配置大一些，比如说 100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true